### ISSUE TITLE
1.3.71 Unstable Release bug after install

### ISSUE THREAD

**Issue by Ezekial711** [greenshot/greenshot#188]
**Describe the bug**
Software version: 1.3.71 - 3055d42689 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2020-04-16 09:20:58 -04:00
OS: Windows 10 1809 x64 build 17763
GDI object count: 28
User object count: 24

Exception: System.Exception
Message: Element not found. (Exception from HRESULT: 0x80070490)

Stack:
   at Windows.UI.Notifications.ToastNotifier.get_Setting()
   at GreenshotWin10Plugin.ToastNotificationService.ShowMessage(String message, Int32 timeout, Action onClickAction, Action onClosedAction) in d:\a\1\s\GreenshotWin10Plugin\ToastNotificationService.cs:line 83
   at Greenshot.MainForm.HandleDataTransport(CopyDataTransport dataTransport) in d:\a\1\s\Greenshot\Forms\MainForm.cs:line 449
   at Greenshot.MainForm..ctor(CopyDataTransport dataTransport) in d:\a\1\s\Greenshot\Forms\MainForm.cs:line 422
   at Greenshot.MainForm.Start(String[] arguments) in d:\a\1\s\Greenshot\Forms\MainForm.cs:line 273

Configuration dump:

**To Reproduce**
1. Install Program
2. Run Program

**Additional context**

**Comment by asvc** [comment]
Duplicate, please refer to https://github.com/greenshot/greenshot/issues/182#issuecomment-613364506

**Comment by Lakritzator** [comment]
Will be solved in aprox an hour from now.

**Comment by Lakritzator** [comment]
Solved with 1.3.75
