### ISSUE TITLE
Exception when copy-pasting text object in the editor

### ISSUE THREAD

**Issue by asvc** [greenshot/greenshot#217]
**Describe the bug**

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture something
2. Open Editor
3. Add a text with the following parameters:  ![image](https://user-images.githubusercontent.com/300146/87299042-763a3780-c54a-11ea-870c-bde3b902ea78.png)

4. Select the text, press <kbd>CTRL+C</kbd> and then <kbd>CTRL+V</kbd>.

**Expected behavior**
New text object is created that is a copy of one from the clipboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/300146/87299182-b4cff200-c54a-11ea-8522-6b3c06a9a1de.png)

**Versions (please complete the following information):**
 - Greenshot version 1.3.105 - 5db1f5564b
 - Windows version 10 1909 x64 build 18363

**Additional context**
Exception output:
```
Software version: 1.3.105 - 5db1f5564b (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2020-07-13 20:47:26 +09:30
OS: Windows 10 1909 x64 build 18363
GDI object count: 92
User object count: 88

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stack:
   at Greenshot.Drawing.TextContainer.SwitchParent(Surface newParent) in d:\a\1\s\Greenshot\Drawing\TextContainer.cs:line 161
   at Greenshot.Drawing.DrawableContainerList.set_Parent(ISurface value) in d:\a\1\s\Greenshot\Drawing\DrawableContainerList.cs:line 109
   at Greenshot.Drawing.Surface.PasteElementFromClipboard() in d:\a\1\s\Greenshot\Drawing\Surface.cs:line 1804
   at Greenshot.ImageEditorForm.PasteToolStripMenuItemClick(Object sender, EventArgs e) in d:\a\1\s\Greenshot\Forms\ImageEditorForm.cs:line 675
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

Configuration dump:
```

**Comment by Lakritzator** [comment]
Nice report, I had all the information I needed to fix this issue.
This fix should be in Greenshot 1.3.111, or later. Available somewhere today/tomorrow.
