### ISSUE TITLE
Crash when trying to Capture Region on Windows 10!

### ISSUE THREAD

**Issue by Skates1616** [greenshot/greenshot#218]
When trying to capture a region on Windows 10, the latest beta of Greenshot throws up an exception:

> Software version: 1.3.105 - 5db1f5564b (64 bit)
> .NET runtime version: 4.0.30319.42000+
> Time: 2020-07-17 07:42:22 -05:00
> OS: Windows 10 2004 x64 build 19041
> GDI object count: 39
> User object count: 35
> 
> Exception: System.NullReferenceException
> Message: Object reference not set to an instance of an object.
> 
> Stack:
>    at GreenshotWin10Plugin.Processors.Win10OcrProcessor.ProcessCapture(ISurface surface, ICaptureDetails captureDetails) in d:\a\1\s\GreenshotWin10Plugin\Processors\Win10OcrProcessor.cs:line 44
>    at Greenshot.Helpers.CaptureHelper.HandleCapture() in d:\a\1\s\Greenshot\Helpers\CaptureHelper.cs:line 645
>    at Greenshot.Helpers.CaptureHelper.CaptureWithFeedback() in d:\a\1\s\Greenshot\Helpers\CaptureHelper.cs:line 1000
>    at Greenshot.Helpers.CaptureHelper.MakeCapture() in d:\a\1\s\Greenshot\Helpers\CaptureHelper.cs:line 443
>    at Greenshot.Helpers.CaptureHelper.CaptureRegion(Boolean captureMouse) in d:\a\1\s\Greenshot\Helpers\CaptureHelper.cs:line 96
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
> 
> Configuration dump:

**Comment by Lakritzator** [comment]
Can you try https://github.com/greenshot/greenshot/releases/tag/v1.3.106 ?

**Comment by Skates1616** [comment]
Same issue:

Software version: 1.3.106 - 6a09345649 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2020-07-20 12:00:31 -05:00
OS: Windows 10 2004 x64 build 19041
GDI object count: 39
User object count: 34

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stack:
   at GreenshotWin10Plugin.Processors.Win10OcrProcessor.ProcessCapture(ISurface surface, ICaptureDetails captureDetails) in d:\a\1\s\GreenshotWin10Plugin\Processors\Win10OcrProcessor.cs:line 49
   at Greenshot.Helpers.CaptureHelper.HandleCapture() in d:\a\1\s\Greenshot\Helpers\CaptureHelper.cs:line 645
   at Greenshot.Helpers.CaptureHelper.CaptureWithFeedback() in d:\a\1\s\Greenshot\Helpers\CaptureHelper.cs:line 1000
   at Greenshot.Helpers.CaptureHelper.MakeCapture() in d:\a\1\s\Greenshot\Helpers\CaptureHelper.cs:line 443
   at Greenshot.Helpers.CaptureHelper.CaptureRegion(Boolean captureMouse) in d:\a\1\s\Greenshot\Helpers\CaptureHelper.cs:line 96
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

Configuration dump:

**Comment by Lakritzator** [comment]
Forgot to mention, this should be solved with the most recent builds by commit https://github.com/greenshot/greenshot/commit/d602433c535dcb34dd1edfbffd2b6a0927e35b9d
