### ISSUE TITLE
Error on Application Launch

### ISSUE THREAD

**Issue by HarryJames-Potter** [greenshot/greenshot#318]
I started getting an error prompt a few days back, when Greenshot would start at system logon. Earlier I could still take screenshots, despite the error. Now, application closes as soon as it displays following error: 

```
Software version: 1.3.205 - 3350120b55 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2021-06-11 08:21:01 +05:30
OS: Windows 10 2009 x64 build 19042
GDI object count: 20
User object count: 17

Exception: System.TypeInitializationException
Message: The type initializer for 'Dapplo.HttpExtensions.HttpExtensionsGlobals' threw an exception.

Stack:
   at Greenshot.Helpers.UpdateService..ctor() in D:\a\1\s\src\Greenshot\Helpers\UpdateService.cs:line 82
   at Greenshot.Forms.MainForm..ctor(CopyDataTransport dataTransport) in D:\a\1\s\src\Greenshot\Forms\MainForm.cs:line 496
   at Greenshot.Forms.MainForm.Start(String[] arguments) in D:\a\1\s\src\Greenshot\Forms\MainForm.cs:line 319
--- InnerException: ---
Exception: System.TypeInitializationException
Message: The type initializer for 'Dapplo.HttpExtensions.ContentConverter.SyndicationFeedHttpContentConverter' threw an exception.

Stack:
   at Dapplo.HttpExtensions.ContentConverter.SyndicationFeedHttpContentConverter.get_Instance() in D:\a\1\s\src\Dapplo.HttpExtensions\ContentConverter\SyndicationFeedHttpContentConverter.cs:line 30
   at Dapplo.HttpExtensions.HttpExtensionsGlobals..cctor() in D:\a\1\s\src\Dapplo.HttpExtensions\HttpExtensionsGlobals.cs:line 26
--- InnerException: ---
Exception: System.IO.FileNotFoundException
Message: Could not load file or assembly 'Dapplo.Log, Version=1.3.0.0, Culture=neutral, PublicKeyToken=26f3e58a2304a05e' or one of its dependencies. The system cannot find the file specified.

Stack:
   at Dapplo.HttpExtensions.ContentConverter.SyndicationFeedHttpContentConverter..cctor()



Configuration dump:

```

**Comment by Lakritzator** [comment]
That looks weird, also that you are the first to report and already quite a lot of people have it installed.
How did you install it? Can you check if all the files are in the installation directory?

This is what it looks like for me, after I installed that version:
![image](https://user-images.githubusercontent.com/708125/122174240-d932fd80-ce82-11eb-8c65-4e81ac8e8d66.png)

You can ignore the greenshot.log and greenshot.log.1 files...

**Comment by HarryJames-Potter** [comment]
Thanks, @Lakritzator. Yes, Dapplo.Log.dll is missing. 

I installed it from releases page: https://github.com/greenshot/greenshot/releases/tag/v1.3.205

![a](https://user-images.githubusercontent.com/75267713/122182702-237aa580-cea8-11eb-97ac-9273f828d54e.png)

I removed the earlier installation, and reinstalled v1.3.205, but still get the same error. 

```
Software version: 1.3.205 - 3350120b55 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2021-06-16 13:27:34 +05:30
OS: Windows 10 2009 x64 build 19042
GDI object count: 20
User object count: 17

Exception: System.TypeInitializationException
Message: The type initializer for 'Dapplo.HttpExtensions.HttpExtensionsGlobals' threw an exception.

Stack:
   at Greenshot.Helpers.UpdateService..ctor() in D:\a\1\s\src\Greenshot\Helpers\UpdateService.cs:line 82
   at Greenshot.Forms.MainForm..ctor(CopyDataTransport dataTransport) in D:\a\1\s\src\Greenshot\Forms\MainForm.cs:line 496
   at Greenshot.Forms.MainForm.Start(String[] arguments) in D:\a\1\s\src\Greenshot\Forms\MainForm.cs:line 319
--- InnerException: ---
Exception: System.TypeInitializationException
Message: The type initializer for 'Dapplo.HttpExtensions.ContentConverter.SyndicationFeedHttpContentConverter' threw an exception.

Stack:
   at Dapplo.HttpExtensions.ContentConverter.SyndicationFeedHttpContentConverter.get_Instance() in D:\a\1\s\src\Dapplo.HttpExtensions\ContentConverter\SyndicationFeedHttpContentConverter.cs:line 30
   at Dapplo.HttpExtensions.HttpExtensionsGlobals..cctor() in D:\a\1\s\src\Dapplo.HttpExtensions\HttpExtensionsGlobals.cs:line 26
--- InnerException: ---
Exception: System.IO.FileNotFoundException
Message: Could not load file or assembly 'Dapplo.Log, Version=1.3.0.0, Culture=neutral, PublicKeyToken=26f3e58a2304a05e' or one of its dependencies. The system cannot find the file specified.

Stack:
   at Dapplo.HttpExtensions.ContentConverter.SyndicationFeedHttpContentConverter..cctor()



Configuration dump:

```

**Comment by Lakritzator** [comment]
This should by solved for a while now, please check the most recent builds found here: https://github.com/greenshot/greenshot/releases

**Comment by jamesd1** [comment]
I installed the latest version on Windows 11 and also get a windows application error at every boot.   I uninstalled and it went away.  I then tried the portable version and got the error; now can't get rid of it by uninstalling!
