### ISSUE TITLE
Imgur button does not do anything useful

### ISSUE THREAD

**Issue by jinek** [greenshot/greenshot#324]
Can not create ticket in Jira as I'm not authorized there

**Describe the bug**
I click button Imgur, it shows the popup "Communicating with Imgur", then it dissapears and nothing happens

**Screenshots**
![image](https://user-images.githubusercontent.com/10516222/125211869-da9ced80-e2a9-11eb-9507-72410705d1c5.png)

**Versions (please complete the following information):**
 - 1.2.10 build 6
 - Windows 10

**Comment by Lakritzator** [comment]
It uploads to imgur, and places the link to Imgur on the clipboard.
If you are using anonymous upload (which is the default) there is also a history, accessible via the context menu (our G icon in the clock area). This allows you to see and delete previous uploads.

I would advice you to use the non anonymous way to upload though, so you can manage your uploads in Imgur itself.
To switch, go to our G icon, right-click, select imgur, select configure and there in the window, disable the anonymous checkbox.
Next time you try to upload, you need to allow access for Greenshot to your Imgur account.

**Comment by jinek** [comment]
May I change this to feature request "show message "url is copied to the clipboard" after uploading to imgur" ?

**Comment by litemotiv** [comment]
> I would advice you to use the non anonymous way to upload though, so you can manage your uploads in Imgur itself.

I don't intend to hijack the ticket but the non anonymous option doesn't seem to work here using 1.3.205, it says:

"Failed to contact Greenshot to inform about the Imgur authorization."

https://i.imgur.com/5KKfr3b.png

**Comment by jinek** [comment]
> 
> 
> > I would advice you to use the non anonymous way to upload though, so you can manage your uploads in Imgur itself.
> 
> I don't intend to hijack the ticket but the non anonymous option doesn't seem to work here using 1.3.205, it says:
> 
> "Failed to contact Greenshot to inform about the Imgur authorization."
> 
> https://i.imgur.com/5KKfr3b.png

Yeah, this is very different story, at least it gives some feedback.

**Comment by Lakritzator** [comment]
The issue here might be due to imgur changing it's interface and we weren't able to release a new version with a fix (due to #264)

Can you please play around with a version which received a lot of improvement, you can find it under the releases in this repository, like here: https://github.com/greenshot/greenshot/releases

**Comment by litemotiv** [comment]
@Lakritzator i've installed the latest compiled version 1.3.211 but unfortunately imgur authentication gives back the same error:

https://i.imgur.com/xFlj42k.png

**Comment by Lakritzator** [comment]
@litemotiv I double checked: it works for me ™️
So we need to know why it doesn't work for you.
Did you get any popups, or error messages?
Maybe your firewall application?

Why? Greenshot will open the default browser (we had many issues with the embedded one), and this needs to communicate back to Greenshot. So Greenshot will briefly open a HTTP listener to get the result from the browser back. Maybe there is an issue with that?

Anything that comes to mind?

Maybe you can check out the logfile? https://getgreenshot.org/faq/where-can-i-find-greenshots-log-file/

**Comment by litemotiv** [comment]
@Lakritzator thank you that was helpful! I believe the browser may have been of influence, i am using Brave browser which may block some traffic by default. I had also tried with Firefox and had similar results, but was using uBlock Origin there so that could have caused a similar problem.

After disabling Brave's "shields up" the authentication seems to have worked. The Greenshot status page still displayed "failed" after accepting the auth dialog on imgur, but the image itself got uploaded to my imgur account:

`[Greenshot.Base.Core.AbstractDestination] Export to Upload to Imgur success, closing menu`

There were no other popups or errors and the Greenshot logs also showed no mention of the earlier oauth failing.

If you need any other information, please let me know and i will try to provide it.

**Comment by Lakritzator** [comment]
Btw. I am glad you found this, it might help me to stabilize the changes before we go live.
I might need to test with Brave!

**Comment by litemotiv** [comment]
@Lakritzator here is the relevant log part:

```
2021-10-16 23:04:07,860 [Greenshot] INFO  - [Greenshot.Helpers.CaptureHelper] Calling processor TitleFix
2021-10-16 23:04:07,860 [Greenshot] INFO  - [Greenshot.Helpers.CaptureHelper] Calling processor Windows10OcrProcessor
2021-10-16 23:04:10,185 [Imgur plug-in] WARN  - [Greenshot.Base.Core.ImageOutput] Using memorystream prevent an issue with saving to a non seekable stream.
2021-10-16 23:04:10,725 [Imgur plug-in] ERROR - [Greenshot.Base.Core.NetworkHelper] HTTP error Unauthorized
2021-10-16 23:04:10,725 [Imgur plug-in] ERROR - [Greenshot.Base.Core.NetworkHelper] Content: <?xml version="1.0" encoding="utf-8"?>
<data type="array" success="0" status="401"><error>Authentication required</error><request>/3/upload.xml</request><method>POST</method></data>

2021-10-16 23:04:10,725 [Imgur plug-in] ERROR - [Greenshot.Base.Core.NetworkHelper] WebException: 
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Greenshot.Base.Core.NetworkHelper.GetResponseAsString(HttpWebRequest webRequest, Boolean alsoReturnContentOnError) in D:\a\1\s\src\Greenshot.Base\Core\NetworkHelper.cs:line 579
2021-10-16 23:04:10,819 [Imgur plug-in] INFO  - [Greenshot.Base.IniFile.IniConfig] Using ini file C:\Users\Mi\AppData\Roaming\Greenshot\Greenshot.ini
2021-10-16 23:04:10,819 [Imgur plug-in] INFO  - [Greenshot.Base.IniFile.IniConfig] Saving configuration to: C:\Users\Mi\AppData\Roaming\Greenshot\Greenshot.ini
2021-10-16 23:04:10,819 [Imgur plug-in] ERROR - [Greenshot.Base.Controls.PleaseWaitForm] invoke error:
System.UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized.
   at Greenshot.Base.Core.NetworkHelper.GetResponseAsString(HttpWebRequest webRequest, Boolean alsoReturnContentOnError) in D:\a\1\s\src\Greenshot.Base\Core\NetworkHelper.cs:line 617
   at Greenshot.Plugin.Imgur.ImgurUtils.UploadToImgur(ISurface surfaceToUpload, SurfaceOutputSettings outputSettings, String title, String filename) in D:\a\1\s\src\Greenshot.Plugin.Imgur\ImgurUtils.cs:line 225
   at Greenshot.Plugin.Imgur.ImgurPlugin.<>c__DisplayClass17_0.<Upload>b__0() in D:\a\1\s\src\Greenshot.Plugin.Imgur\ImgurPlugin.cs:line 198
   at Greenshot.Base.Controls.PleaseWaitForm.<>c__DisplayClass7_0.<ShowAndWait>b__0() in D:\a\1\s\src\Greenshot.Base\Controls\PleaseWaitForm.cs:line 90
2021-10-16 23:04:10,866 [Greenshot] ERROR - [Greenshot.Plugin.Imgur.ImgurPlugin] Error uploading.
System.UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized.
   at Greenshot.Base.Controls.PleaseWaitForm.ShowAndWait(String title, String text, ThreadStart waitDelegate) in D:\a\1\s\src\Greenshot.Base\Controls\PleaseWaitForm.cs:line 127
   at Greenshot.Plugin.Imgur.ImgurPlugin.Upload(ICaptureDetails captureDetails, ISurface surfaceToUpload, String& uploadUrl) in D:\a\1\s\src\Greenshot.Plugin.Imgur\ImgurPlugin.cs:line 209
2021-10-16 23:04:13,700 [Greenshot] INFO  - [Greenshot.Base.Core.AbstractDestination] Export cancelled or failed, showing menu again
```

Interestingly, as a test i tried revoking the auth on the imgur website to try reauthorizing from Greenshot, but Greenshot keeps giving the same error. So it appears that Greenshot cannot determine that the auth was revoked remotely.

**Comment by ReXNeB77** [comment]
> @Lakritzator thank you that was helpful! I believe the browser may have been of influence, i am using Brave browser which may block some traffic by default. I had also tried with Firefox and had similar results, but was using uBlock Origin there so that could have caused a similar problem.
> 
> After disabling Brave's "shields up" the authentication seems to have worked. The Greenshot status page still displayed "failed" after accepting the auth dialog on imgur, but the image itself got uploaded to my imgur account:
> 
> `[Greenshot.Base.Core.AbstractDestination] Export to Upload to Imgur success, closing menu`
> 
> There were no other popups or errors and the Greenshot logs also showed no mention of the earlier oauth failing.
> 
> If you need any other information, please let me know and i will try to provide it.

My problem with IMGUR was also related to Brave : At the first time auth (don't use Google Auth) you have to disable Brave Shield for both UMGUR and GREENSHOT websites

After the AUTH / ALLOW done you can switch Brave Shield back to ON on both websites and have working Screenshots Uploads
