### ISSUE TITLE
Image Editor crashes when pressing `CTRL`+`DELETE`

### ISSUE THREAD

**Issue by lupinitylabs** [greenshot/greenshot#335]
**Describe the bug**
When pressing `CTRL`+`DELETE`, the Image Editor crashes with a stack trace.
Noticed it when I was working on #334. If you like, assign me to the issue and I'll give it a look.

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture a screenshot
2. Open Editor
3. Press `CTRL`+`DELETE`
4. Behold the Error Form.

**Expected behavior**
According to the source code it should grayscale the image? The documentation doesn't seem to list it though.

```C#
case Keys.Delete: // Grayscale Ctrl + Delete
    ClearToolStripMenuItemClick(sender, e);
    break;
```

**Versions (please complete the following information):**
 - Current HEAD of release/1.3
 - Windows version: 10 Enterprise

**Additional context**

Stack trace:

```
Software version: 1.3.216 - 8ef14c6049 (64 bit)
.NET runtime version: 4.0.30319.42000+
OS: Windows 10 1809 x64 build 17763
GDI object count: 86
User object count: 88

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stack:
   at Greenshot.Editor.Memento.SurfaceBackgroundChangeMemento..ctor(Surface surface, Matrix matrix) in C:\...\src\Greenshot.Editor\Memento\SurfaceBackgroundChangeMemento.cs:line 42
   at Greenshot.Editor.Drawing.Surface.Clear(Color newColor) in C:\...\src\Greenshot.Editor\Drawing\Surface.cs:line 961
   at Greenshot.Editor.Forms.ImageEditorForm.ImageEditorFormKeyDown(Object sender, KeyEventArgs e) in C:\...\src\Greenshot.Editor\Forms\ImageEditorForm.cs:line 1037
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Lakritzator** [comment]
Thanks, good to know, I'll look at it.
P.S.
It should not do grayscale, that must be a comment which got copied.

**Comment by Lakritzator** [comment]
Not hard at all, but I had a big laugh. This is pretty much an undocumented feature and removes the background (which is the capture) and replaces it with a transparent color. I have no idea why we have this, and you know the worst, I seem to have added it.

Anyway, I fixed it and it will work with the next build. The commit will
