### ISSUE TITLE
Exception when double a text field in a previously saved .greenshot file

### ISSUE THREAD

**Issue by d0vgan** [greenshot/greenshot#414]
**Describe the bug**
I have a previously saved .greenshot file. Please see the attached zipped file:
[IRule.greenshot.zip](https://github.com/greenshot/greenshot/files/8879215/IRule.greenshot.zip)
In this example, I tried to use GreenShot for a sort of a simple UML diagram :)

**To Reproduce**
Example steps to reproduce the behavior:
1. Open the  .greenshot file in GreenShot. I tried the versions 1.3.258 and 1.3.259.
2. Double-click a text field - for example, the one that says "getRuleType()" or "getAppName()"
3. As the result, GreenSHot shows an exception:

```
Software version: 1.3.259 - 3f6f9863f8 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2022-06-10 16:31:43 +03:00
OS: Windows 10 2009 x64 build 19044
GDI object count: 60
User object count: 72

Exception: System.ArgumentException
Message: Parameter is not valid.

Stack:
   at System.Drawing.Font.ToLogFont(Object logFont, Graphics graphics)
   at System.Drawing.Font.ToLogFont(Object logFont)
   at System.Drawing.Font.ToHfont()
   at System.Windows.Forms.Control.FontHandleWrapper..ctor(Font font)
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.Control.SetWindowFont()
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.TextBoxBase.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.TextBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Configuration dump:

```

**Expected behavior**
There should be no exception, the test field should allow to change the text.

**Versions (please complete the following information):**
 - Greenshot version 1.3.258 and 1.3.259
 - Windows version Windows 10 64-bit 21H2 build 19044.1706

**Additional context**

**Comment by d0vgan** [comment]
Here is the same exception on another PC (also Windows 10 Pro, 21H2, 19044.1706, 64-bit):
```
Software version: 1.3.259 - 3f6f9863f8 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2022-06-11 12:10:45 +03:00
OS: Windows 10 2009 x64 build 19044
GDI object count: 105
User object count: 84

Exception: System.ArgumentException
Message: Parameter is not valid.

Stack:
   at System.Drawing.Font.ToLogFont(Object logFont, Graphics graphics)
   at System.Drawing.Font.ToLogFont(Object logFont)
   at System.Drawing.Font.ToHfont()
   at System.Windows.Forms.Control.FontHandleWrapper..ctor(Font font)
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.Control.SetWindowFont()
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.TextBoxBase.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.TextBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Configuration dump:

```

**Comment by d0vgan** [comment]
Interestingly, when I build a Debug version of Greenshot and either start debugging from Visual Studio or attach to an already running instance of Greenshot.exe, I still see the same exception. Does it mean the exception comes from some internals of .NET? And if so, how can one debug it?

**Comment by d0vgan** [comment]
Well, I believe the problem starts somewhere here:

![CreateTextBox](https://user-images.githubusercontent.com/2848457/173183366-73368fa7-48a3-487c-bef4-013af22659f9.jpg)

The value looks strange: `FontHandle = 0xffffffffe40a12ab`.

And the exception is thrown here:

![ShowTextBox](https://user-images.githubusercontent.com/2848457/173183630-f7f1fba9-85c1-4879-9e2d-4d4fec588905.jpg)

You know, I had some experience with C#, but these things around the font looks like a complete mystery to me. Where the value of the `FontHandle` initially comes from? How can it be that this value can't be read later? I have no idea...

**Comment by Lakritzator** [comment]
Just a quick remark, if you are using Greenshot 1.3 and try to read .greenshot files from older versions, that will not work. This is something I am looking at, but we will need a complete new file format and also write converters for the older versions.

That is something you can follow here: https://github.com/greenshot/greenshot/issues/375

If this is not what you mean with "I have a previously saved .greenshot file", we will need to look at it, but still the file writing and reading needs some love.

**Comment by d0vgan** [comment]
I think I've created it using either 1.3.258 or 1.3.256.

**Comment by Lakritzator** [comment]
Ok, so it's clear that this has nothing to do with the known bug of opening .greenshot files from much older versions.
I need to see what we did, I think it's possible I've changed some of the things that are written to the file, and thus while reading this back it will no longer fit and cause issues.

**Comment by Mattschu** [comment]
I got the same exception with a newer version now. The file was saved and tried to modify with the same version within 2 weeks.
When opening the file and trying to edit a text by double clicking it, a Error window popped up with the below exception information.
I tried with different files and with different text fields and different content.
Even saving a .greenshot file, closing Grennshot and then opening the saved file, I get this error on the first try to editing the text. On the following trials I am able to edit.


Software version: 1.3.312 - 5a60aff83e (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2026-06-02 13:20:06 +02:00
OS: Windows 10 2009 x64 build 26100
GDI object count: 106
User object count: 85

Exception: System.ArgumentException
Message: Parameter is not valid.

Stack:
   at System.Drawing.Font.ToLogFont(Object logFont, Graphics graphics)
   at System.Drawing.Font.ToLogFont(Object logFont)
   at System.Drawing.Font.ToHfont()
   at System.Windows.Forms.Control.FontHandleWrapper..ctor(Font font)
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.Control.SetWindowFont()
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.TextBoxBase.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.TextBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Configuration dump:
