### ISSUE TITLE
Powerpoint not available as destination

### ISSUE THREAD

**Issue by Ossy81** [greenshot/greenshot#424]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**
When taking snapshots i was able to send it to powerpoint, but now most of the office destinations are gone. Only Word is still there.

**To Reproduce**
1. Capture 'area
2. In the list PowerPoint is missing

**Screenshots**
![image](https://user-images.githubusercontent.com/31192617/178826581-c16784bf-3509-47ad-81cf-3079d88c2e9d.png)

**Versions (please complete the following information):**
 - Greenshot version: 1.3.249
 - Windows version: 11

**Comment by Lakritzator** [comment]
Works fine for me, are you sure Powerpoint is still on the system?
I also advice you to upgrade, you are on an older unstable version.

**Comment by Ossy81** [comment]
> Works fine for me, are you sure Powerpoint is still on the system? I also advice you to upgrade, you are on an older unstable version.

Yes it is. Thought this was the latest version. Where can I download the latest installer?

**Comment by Lakritzator** [comment]
The "betas" are always in our GitHub releases, which can be found here: https://github.com/greenshot/greenshot/releases

Can you give me some details how you installed office?

**Comment by Lakritzator** [comment]
@Ossy81 we made changes to Greenshot, which are available with 1.3.270 and later, can you please see if this works for you?

**Comment by Ossy81** [comment]
@Lakritzator just uninstalled greenshot. removed all files/folder/registers etc.. and installed it as admin. Now i can see PowerPoint again. So it looks like it's working :) But it feels a bit slow.. Could be also my laptop.. 

But sometimes (was also before) getting this error:
Software version: 1.3.270 - 511034a34b (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2022-09-20 21:25:16 +02:00
OS: Windows 10 2009 x64 build 22621
GDI object count: 78
User object count: 48

Exception: System.Runtime.InteropServices.COMException
Message: Retrieving the COM class factory for component with CLSID {91493441-5A91-11CF-8700-00AA0060263B} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).

ErrorCode: 0x80080005

Stack:
   at System.Runtime.Remoting.RemotingServices.AllocateUninitializedObject(RuntimeType objectType)
   at System.Runtime.Remoting.Activation.ActivationServices.CreateInstance(RuntimeType serverType)
   at System.Runtime.Remoting.Activation.ActivationServices.IsCurrentContextOK(RuntimeType serverType, Object[] props, Boolean bNewObj)
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Greenshot.Plugin.Office.OfficeExport.PowerpointExporter.GetOrCreatePowerPointApplication() in D:\a\1\s\src\Greenshot.Plugin.Office\OfficeExport\PowerpointExporter.cs:line 236
   at Greenshot.Plugin.Office.OfficeExport.PowerpointExporter.InsertIntoNewPresentation(String tmpFile, Size imageSize, String title) in D:\a\1\s\src\Greenshot.Plugin.Office\OfficeExport\PowerpointExporter.cs:line 334
   at Greenshot.Plugin.Office.Destinations.PowerpointDestination.ExportCapture(Boolean manuallyInitiated, ISurface surface, ICaptureDetails captureDetails) in D:\a\1\s\src\Greenshot.Plugin.Office\Destinations\PowerpointDestination.cs:line 147
   at Greenshot.Base.Core.AbstractDestination.<>c__DisplayClass28_0.<ShowPickerMenu>b__4(Object sender, EventArgs e) in D:\a\1\s\src\Greenshot.Base\Core\AbstractDestination.cs:line 257
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Configuration dump:

**Comment by Lakritzator** [comment]
Removed registers? There is only one registry key that Greenshot should be setting, and that is the one for the auto start.
In fact, Greenshot really has a small footprint on the system itself, that is why you could even run Greenshot from a directory where the files were copied to 😉 

The error is quite weird, I just checked the code and found that Greenshot first looks if it can communicate with a running PowerPoint instance, and where this fails it tries to create an instance. This second step, seems to be the place where you sometimes get the error. I should hold the error (catch it) and make sure you are not bothered by it, but then it still doesn't work... 

Do you have any idea if PowerPoint was running, or if sometimes it just takes long for PowerPoint to start?
Maybe there were some popups involved? Or does PowerPoint run under a different user?

Anything else that might be out of the ordinary?

**Comment by Ossy81** [comment]
Hi Robin,

I just wanted to do a clean install and removed wvr8with greenshot in it 😁

Hmm as said could be my laptop. Going to test it tomorrow again after a
restart. PowerPoint was indeed slow. So something could cause this error.
Will let you know if I face any issues.

BTW there is 1 point 😊not sure if it's easy, but I use greenshot to make
Screenshot of apps and send it to powepint to put comments/feedback to it.
Sometime the Screenshot don't fit on the page. So I need to make them
smaller. Would it be possible to make. Them always fit in PowerPoint sheet?

**Comment by Ossy81** [comment]
This issue is solved btw.
Is there anyone who could help with creating a PowerPoint template? So when you send the screenshot to powerpoint i would like to have a particular layout
