### ISSUE TITLE
Error During Activity - notification bug?

### ISSUE THREAD

**Issue by TheDarkAngel666** [greenshot/greenshot#479]
**Describe the bug**
Dump, unexpected error

**To Reproduce**
1. Capture with stamp
2 . Open in image editor
3 . Error window
4 . It's opening anyway the editor
5 . Do something like arrows/text/ecc
6 . send to clipboard
7 . correctly send to clipboard but another error

**Expected behavior**
No windows error

**Screenshots**
![immagine](https://user-images.githubusercontent.com/25157234/228822851-d342e2a8-9b1d-43e2-acd8-1c9bd9beac2a.png)

**Versions (please complete the following information):**
 - Greenshot version 1.3.274 / 277
 - Windows version 11 Pro 22624.1470

**Additional context**
Error log:
Software version: 1.3.274 - 7e005f741a (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2023-03-30 13:22:55 +02:00
OS: Windows 10 2009 x64 build 22624
GDI object count: 111
User object count: 91

Exception: System.InvalidOperationException
Message: Failed initializing notifications

Stack:
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Greenshot.Plugin.Win10.ToastNotificationService.ShowMessage(String message, Nullable`1 timeout, Action onClickAction, Action onClosedAction) in D:\a\1\s\src\Greenshot.Plugin.Win10\ToastNotificationService.cs:line 179
   at Greenshot.Plugin.Win10.ToastNotificationService.ShowInfoMessage(String message, Nullable`1 timeout, Action onClickAction, Action onClosedAction) in D:\a\1\s\src\Greenshot.Plugin.Win10\ToastNotificationService.cs:line 200
   at Greenshot.Helpers.CaptureHelper.SurfaceMessageReceived(Object sender, SurfaceMessageEventArgs eventArgs) in D:\a\1\s\src\Greenshot\Helpers\CaptureHelper.cs:line 663
   at Greenshot.Base.Interfaces.SurfaceMessageEventHandler.Invoke(Object sender, SurfaceMessageEventArgs e)
   at Greenshot.Base.Core.AbstractDestination.ProcessExport(ExportInformation exportInformation, ISurface surface) in D:\a\1\s\src\Greenshot.Base\Core\AbstractDestination.cs:line 131
   at Greenshot.Destinations.ClipboardDestination.ExportCapture(Boolean manuallyInitiated, ISurface surface, ICaptureDetails captureDetails) in D:\a\1\s\src\Greenshot\Destinations\ClipboardDestination.cs:line 74
   at Greenshot.Editor.Forms.ImageEditorForm.BtnClipboardClick(Object sender, EventArgs e) in D:\a\1\s\src\Greenshot.Editor\Forms\ImageEditorForm.cs:line 661
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at Greenshot.Editor.Controls.ToolStripEx.WndProc(Message& m) in D:\a\1\s\src\Greenshot.Editor\Controls\ToolStripEx.cs:line 60
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
--- InnerException: ---
Exception: System.IO.IOException
Message: Cannot create a stable subkey under a volatile parent key.

Stack:
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()

Configuration dump:

---
**Stack Trace Hash:** [628e30c7e1d0]

**Comment by TheDarkAngel666** [comment]
without this option is working flawless:
![immagine](https://user-images.githubusercontent.com/25157234/228823573-74656682-8737-4d16-8f96-5d58ee9201ff.png)

**Comment by Lakritzator** [comment]
The error in the stack trace would assume your windows setup is (a bit) broken.
```
Exception: System.IO.IOException
Message: Cannot create a stable subkey under a volatile parent key.
```

This means that the notification logic tries to create a registry key at a location which was incorrectly created.
There is a whole blog-post about such issues: https://devblogs.microsoft.com/oldnewthing/20170525-00/?p=96225

The problem is that it doesn't explain why/how this happend for your case and if we can prevent it.
I will need to check the sources of the Microsoft toolkit, to see where they try to create the registry entry, so we can fix this.

**Comment by shawn-hst** [comment]
@Lakritzator @TheDarkAngel666 I had this same issue with a new install of Windows 11. I was able to fix this by unchecking the Windows 10 plugin during the install. After reinstalling with that unchecked I was able to get the notifications again with out that error.

**Comment by vv211** [comment]
> is means that the notification logic tries to create a registry key at a location which was incorrectly created.
> There is a whole blo

thanks, this fixed the error for me as well
